# Generated by Django 6.0.4 on 2026-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Capacity in Liters', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
