# Generated by Django 6.0.4 on 2026-05-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_branch_rename_price_per_day_car_daily_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='branch',
        ),
    ]
