# Generated by Django 6.0.4 on 2026-05-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
