# Generated by Django 6.0.4 on 2026-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='interior_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='cars/interiors/'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='cars/interiors/'),
        ),
    ]
